#cloud-config
password: devpass
ssh_pwauth: true
chpasswd:
  expire: false

users:
- name: dev-user
  shell: /bin/bash
  sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
  lock_passwd: false
  passwd: $6$dev$eTPvIYDPmL9BLh1twZV3.8psTkGv2qp8G9X1.KvB8y

hostname: dev-environment
