name: Build Cloud Images with Packer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: '1.8.4'

      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y qemu-kvm libvirt-daemon-system bridge-utils virt-manager curl

      - name: Download Ubuntu ISO
        run: |
          curl -L -o /tmp/ubuntu-20.04.6-live-server-amd64.iso https://releases.ubuntu.com/20.04/ubuntu-20.04.6-live-server-amd64.iso

      - name: Run Packer build for dev environment
        env:
          PACKER_LOG: 1
        run: |
          packer build -var "env=dev" -var "iso_url=/tmp/ubuntu-20.04.6-live-server-amd64.iso" template.json

      - name: Run Packer build for test environment
        env:
          PACKER_LOG: 1
        run: |
          packer build -var "env=test" -var "iso_url=/tmp/ubuntu-20.04.6-live-server-amd64.iso" template.json

      - name: Run Packer build for prod environment
        env:
          PACKER_LOG: 1
        run: |
          packer build -var "env=prod" -var "iso_url=/tmp/ubuntu-20.04.6-live-server-amd64.iso" template.json
